name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Use .NET 3.1.200
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      - name: Building
        run: |
          dotnet build MathCore.EF7/MathCore.EF7.csproj --nologo
          dotnet build Tests/MathCore.EF7.Tests/MathCore.EF7.Tests.csproj --nologo
          
      - name: Testing
        run: dotnet test Tests/MathCore.EF7.Tests/MathCore.EF7.Tests.csproj --nologo

      - name: Packing
        run: dotnet pack MathCore.EF7/MathCore.EF7.csproj -c Release -v m
         
      - name: Publishing
        run: dotnet nuget push MathCore.EF7/bin/Release/*.nupkg -k ${{ secrets.NuGetApiKey }} --skip-duplicate -s https://api.nuget.org/v3/index.json
