name: Testing

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

      - name: Building
        run: |
          dotnet build MathCore.EF7/MathCore.EF7.csproj --nologo          
          dotnet build Tests/MathCore.EF7.Tests/MathCore.EF7.Tests.csproj --nologo
          
      - name: Run Tests
        run: dotnet test Tests/MathCore.EF7.Tests/MathCore.EF7.Tests.csproj --nologo
